### ISSUE TITLE
Web server crashes in big directory

### ISSUE THREAD

**Issue by Hollow-Onion** [terreng/simple-web-server#107]
Hi,

I was using web-server-for-chrome on a couple of my projects and was looking to migrate them over to simple-web-server instead to prevent future conflicts, however the server always seems to crash if there are a lot of files in the directory it is trying to display.

For context: we are a small radio station that generates XML-Files for every hour of content we stream and I had built a small application which extracts this info out of these files and saves them in a database for later evaluation. I was using web-server-for-chrome to let my program access the files and it worked without a hitch. However, simple-web-server consistently crashes every time I try to access that directory. I suspect that the large amount of files is the problem (around 21'000 and growing) and even with the static file view it can't handle the strain. 

![image](https://user-images.githubusercontent.com/117974496/201293606-0058a7b9-2f73-47a5-a21f-a3f9ea1668ad.png)

![image](https://user-images.githubusercontent.com/117974496/201293771-6997958a-efbe-4418-afb0-ca1def416823.png)

Thank you in advance!

**Comment by ethanaobrien** [comment]
We'll probably need to have like 100 files per page, and have a next button at the bottom. @Hollow-Onion how do you feel about that?

**Comment by Hollow-Onion** [comment]
As long as it I could still fetch the files with http://{IP Adress}:{Port}/{filename} that would work for me. Thank you for your quick response, you're doing amazing work.

**Comment by terreng** [comment]
@Hollow-Onion Thanks for bringing our attention to this issue! It's cool to hear how you intend to use the program.

@ethanaobrien Have you been able to reproduce this issue to confirm that it's a matter of having too large a number of files?

**Comment by ethanaobrien** [comment]
No I haven't, but it makes sense having a string that large is going to have problems

**Comment by terreng** [comment]
That's a good hypothesis. The first thing you need to do is confirm that hypothesis by reproducing the issue with a large number of files. Only then, once you have confirmed the problem, can you start to fix it. If you don't do this first, then you'd have no way of measuring if your fix actually resolved the problem. Make sense? So start by reproducing the issue, and then make sure your fix makes that issue go away.

**Comment by ethanaobrien** [comment]
Yeah, that is planned. I do also need to do what I suggested because it made me think of another big problem - over a certain file size some browsers will refuse to parse the html file, so even if the large strings server side aren't the problem, they can be a problem client side

**Comment by terreng** [comment]
We know the problem in this case is server-side because the program locks up or crashes. I don't know of any browsers that have a set limit on html file size.

**Comment by ethanaobrien** [comment]
It still wouldn't be a bad idea to break up large amounts of files into multiple pages. I've had large html files that don't render or run any scripts because it's too big. I will debug this and fix the problem and possibly do this, like maybe 500 files per page

**Comment by terreng** [comment]
Paging makes sense, just from a usability perspective. Sounds good. I just want to make sure we fix the actual issue.

**Comment by ethanaobrien** [comment]
Hey @terreng could you test this? I made a directory with 1000000 text files and couldn't get the web server to stop responding. The problem for me was all server side, it has a 2 second download time and didn't ever render

**Comment by terreng** [comment]
Hmm. I'm on a Mac, so if it has to do with something about the filesystem when there are so many files, my testing might not be representative.

**Comment by terreng** [comment]
@Hollow-Onion Would it be possible for you to provide a ZIP file of all of the files in the directory? _**Please feel free to say no.**_ If you are completely willing to share, then let us know and I will provide a way for you to send it to us directly instead of posting publicly on GitHub.

If not, then could you do a little bit of testing for us? Could you make a new directory with a much smaller number of the files, and see if you have the same issue? Could you maybe try and find out about how many files it takes before the program stops working for you? Thank you!

**Comment by Hollow-Onion** [comment]
@terreng I don't mind providing you with a zip of the files, just not publicly on GitHub. I just ask that you delete them after testing is complete. I'll have them ready, just tell me where I should send them to you. Thank you!

**Comment by Hollow-Onion** [comment]
I just shared the files over Dropbox, hope that helps!

**Comment by terreng** [comment]
@Hollow-Onion Thank you very much! Hopefully we'll be able to recreate the issue, and then fix it as soon as possible.

@ethanaobrien I just emailed you a link to the ZIP file. Could you please test again with those files, and see if you can recreate the issue?

**Comment by ethanaobrien** [comment]
@terreng I never received an email? Which address did you send it to?

You can email me at either ethan.a.obrien@gmail.com or emulatorjs.ethanaobrien@gmail.com  I check both of these emails equally

**Comment by terreng** [comment]
I just forwarded it to that address. If you still don't see it, check spam.

**Comment by terreng** [comment]
@ethanaobrien Just wanted to see if you've had a chance to look at this

**Comment by ethanaobrien** [comment]
Sorry, I haven't had a chance yet to look at this

**Comment by ethanaobrien** [comment]
@terreng I cannot reproduce this issue with the same files either.

@Hollow-Onion Do you have a SSD or a HDD? This is probably the reason I cannot produce this. This could be because of disk read speed issues, but I cannot diagnose this.

**Comment by ethanaobrien** [comment]
Wait, sorry. I traced and found the issue. It is specific to windows

**Comment by terreng** [comment]
@Hollow-Onion We've fixed the issue, and the fix will be included in the next update (version 1.2.0) later this month or next month. Thanks for reporting this issue!

**Comment by terreng** [comment]
Version 1.2.0 has been released today and includes the fix for this issue. It's available for direct download from [simplewebserver.org](https://simplewebserver.org) today, and and update will be available through the Microsoft Store soon.
