### ISSUE TITLE
Website dark mode

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#116]
Dark mode toggle for the vuepress site

**Comment by terreng** [comment]
@ethanaobrien I saw you set up dark mode for emulatorjs.org! Would you mind opening a PR to add whatever code/plugin you used so that we can add dark mode to the simplewebserver.org site?

**Comment by ethanaobrien** [comment]
Yeah, I'll get this done

**Comment by ethanaobrien** [comment]
@terreng I dont see any changes on the site yet, ddo you need to manually deploy

**Comment by terreng** [comment]
Good catch. The Cloudflare Pages automatic build failed and it didn't notify me. I just had to update the Node version to fix it. Thanks!
