### ISSUE TITLE
Help us translate!

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#124]
Want to help us make Simple Web Server available in more languages? We appreciate your help!

1. Edit [lang.js](https://github.com/terreng/simple-web-server/blob/main/lang.js) to add another language.
2. Create a new issue or pull request on GitHub.

Please also translate the following for our website and the app store description:

> Create local web servers in just a few clicks with an easy-to-use interface.
> 
> Easy to configure
> Change server options with just a few clicks.
> 
> Run multiple & in the background
> Run multiple web servers at the same time, even when the app is closed.
> 
> Single Page Applications
> Enable mod rewrite for SPAs with a single click.

**Comment by Melvovin** [comment]
Français (French)
Créez des serveurs Web locaux en quelques clics avec une interface facile à utiliser.

Facile à configurer
Modifiez les options du serveur en quelques clics.

Exécuter plusieurs et en arrière-plan
Exécutez plusieurs serveurs Web en même temps, même lorsque l'application est fermée.

Demandes d'une seule page
Activez la réécriture de mode pour les SPA en un seul clic.

**Comment by terreng** [comment]
@Melvovin Thanks! Were you planning to translate the file lang.js?

**Comment by pferrucci** [comment]
Hum, you should use the following for the last 2 lines in French. These concepts are known with their names so they are difficult to translate. I had to try your server to be sure about the translation. And yes, I'll now translate the .js file too :-)

Applications monopages (SPA)
Activez la réécriture des chemins pour les SPA en un seul clic.

**Comment by pferrucci** [comment]
While I'm here, here is the Italian version:

Italiano (Italian)
Create server Web locali in pochi clic con un'interfaccia facile da usare.

Facile da configurare
Modificate i settaggi del server in pochi clic.

Esecuzione di più server in background
Eseguite più server Web contemporaneamente, anche quando l'applicazione è chiusa.

Applicazioni pagina singola (SPA)
Abilitate la riscrittura dei percorsi per le SPA con un solo clic.

**Comment by terreng** [comment]
@pferrucci Thanks for providing the Italian translation and correction for the French translation. Because the app hasn't been translated into either of these languages yet, we won't use the translation you provided anywhere yet. If you'd like to help us translate into additional languages, you can create a pull request to update [lang.js](https://github.com/terreng/simple-web-server/blob/main/lang.js). Thanks!

**Comment by vespina** [comment]
Español / Spanish:

Crear servidores web locales con solo unos pocos clicks, con una interfaz fácil de usar.

Fácil de configurar
Cambie las opciones del servidor con solo unos pocos clicks.

Ejecute múltiples & en segundo plano
Ejecute múltiples servidores web al mismo tiempo, incluso cuando la app esta cerrada.

Aplicaciones de Una Página
Active mod rewrite para SPAs con un solo click.

**Comment by vespina** [comment]
> Español / Spanish:
> 
> Crear servidores web locales con solo unos pocos clicks, con una interfaz fácil de usar.
> 
> Fácil de configurar Cambie las opciones del servidor con solo unos pocos clicks.
> 
> Ejecute múltiples & en segundo plano Ejecute múltiples servidores web al mismo tiempo, incluso cuando la app esta cerrada.
> 
> Aplicaciones de Una Página Active mod rewrite para SPAs con un solo click.

Somehow the guide text in the "Help us translate" page seems to be outdated compared to what is being shown on the main readme.me.  Here is a better translation than the one showing now on the Spanish readme:


# Simple Web Server

[Descargar](https://simplewebserver.org/download/) &bull; [Documentación](https://simplewebserver.org/docs/options.html) &bull; [Generar desde el fuente](https://simplewebserver.org/docs/build.html)

Cree servidores web locales con solo unos pocos clicks, con una interfaz de usuario fácil de usar.  Hecho con Electron.

Caracterīsticas:
- Facil de personalizar
- Permite ejecutar varios servidores web simultáneamente
- Incluye soporte para aplicaciones de una sola página (SPA)
- Puede ejecutar en segundo plano

**Comment by vespina** [comment]
> > Español / Spanish:
> > Crear servidores web locales con solo unos pocos clicks, con una interfaz fácil de usar.
> > Fácil de configurar Cambie las opciones del servidor con solo unos pocos clicks.
> > Ejecute múltiples & en segundo plano Ejecute múltiples servidores web al mismo tiempo, incluso cuando la app esta cerrada.
> > Aplicaciones de Una Página Active mod rewrite para SPAs con un solo click.
> 
> Somehow the guide text in the "Help us translate" page seems to be outdated compared to what is being shown on the main readme.md. Here is a better translation than the one showing now on the Spanish readme:
> 
> # Simple Web Server
> [Descargar](https://simplewebserver.org/download/) • [Documentación](https://simplewebserver.org/docs/options.html) • [Generar desde el fuente](https://simplewebserver.org/docs/build.html)
> 
> Cree servidores web locales con solo unos pocos clicks, con una interfaz de usuario fácil de usar. Hecho con Electron.
> 
> Caracterīsticas:
> 
> * Facil de personalizar
> * Permite ejecutar varios servidores web simultáneamente
> * Incluye soporte para aplicaciones de una sola página (SPA)
> * Puede ejecutar en segundo plano

Oh, I see now the problem.. that text on the "Help us translate" is for the main simplewebserver.org site.... ok.  Here is a better text for that site:

Cree servidores web locales con solo unos pocos clicks y con una interfaz fácil de usar.

Fácil de configurar 
Cambie las opciones del servidor con solo unos pocos clicks.

Soporte para multiprocesos & ejecución en segundo plano
Ejecute múltiples servidores web al mismo tiempo, incluso cuando la app esta cerrada.

Aplicaciones de Una Página 
Active el mod rewrite para SPAs con un solo click.

**Comment by terreng** [comment]
Thanks! I've added the updated translations. @vespina

**Comment by terreng** [comment]
@yurtpage 
> Please integrate a translation service like Weblate, Crowdwin, Transifex, Localise.com, PoEditor.com etc. That will simplify translation significantly.

I agree that one of these services would make translating easier, but it would cost money. This is a free project I work on in my spare time and unfortunately no one has provided financial support. If you know of a translation tool that we could use for free, please let me know! Otherwise we'll continue to use pull requests on GitHub.

**Comment by terreng** [comment]
@yurtpage Thanks for the suggestion and for making me aware that it's free for open source! I tried both Crowdin and Weblate, and I think Weblate will work best for this project. Here it is: https://hosted.weblate.org/projects/simple-web-server/simple-web-server/
