### ISSUE TITLE
EADDRINUSE should be caught (currently fatal)

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#13]
`Error: listen EADDRINUSE: address already in use <IP>`

**Comment by ethanaobrien** [comment]
Try surrounding the server.listen() function with a try and catch(e). It should catch it

**Comment by ethanaobrien** [comment]
The only problem is putting this error in the UI

**Comment by terreng** [comment]
I'm thinking that each server should have a state, other than just enabled/disabled.
Possible states:
Disabled
Enabled (starting)
Enabled (errored)
Enabled (running)

**Comment by ethanaobrien** [comment]
@terreng How would we send the thing to update the UI

**Comment by ethanaobrien** [comment]
@terreng Just to make sure, did you see that I found where the error is showing up?

**Comment by terreng** [comment]
Yeah, I just need to make it update the UI
