### ISSUE TITLE
Fenix webserver

### ISSUE THREAD

**Issue by stokito** [terreng/simple-web-server#131]
I just want let you know about a similar project [Fenix](https://github.com/coreybutler/fenix). Maybe you can grab some ideas or even collaborate.
It would be nice to mention it in README so that users may chose what is better fits their needs.

**Comment by terreng** [comment]
Thanks for letting us know about that project. Simple Web Server is a completely free and open source community project. Based on the fact that Fenix have a pricing section on their website, I think their program might be aimed a little bit differently than this one. We won't be endorsing that project at this time.
