### ISSUE TITLE
Dual http and https

### ISSUE THREAD

**Issue by stokito** [terreng/simple-web-server#135]
In order to support the LetsEncrypt certbot we need both http and https. The ACME webroot challenge will check files in the http://example.com/.well-known/ and it doesn't work over https.

As a workaround a user may create two servers but maybe this should be one instead.

**Comment by terreng** [comment]
This is only applicable if you're using Simple Web Server to host a website on the public internet, right?

**Comment by stokito** [comment]
Yes. I was a little bit wrong: the LE can run the webroot challenge on HTTPS but it anyway will first try to do that over plain HTTP but then should be redirected to https.
So in the simplest form the issue can be solved with a new option: Redirect to https

**Comment by terreng** [comment]
Having dual http and https on the same server feels too niche to me given that
\- SWS isn't designed to be used to host public websites
\- It's already entirely possible to this just by creating two servers

An option to redirect to https would just be an option to redirect to any other origin. Here, I made a plugin that can do it:
[redirect plugin.zip](https://github.com/terreng/simple-web-server/files/12197866/redirect.plugin.zip)

**plugin.json**
```
{
  "name": "Redirect",
  "id": "redirect",
  "script": "script.js",
  "options": [
    {
      "id": "origin",
      "name": "Destination URL origin",
      "description": "The destination URL not including the path. For example: <code>https://www.example.com</code>",
      "type": "string",
      "default": "https://www.example.com"
    },
    {
      "id": "path",
      "name": "Include path",
      "description": "If enabled, the path of the original URL will be appended to the destination URL. For example: <code>http://127.0.0.1:80/path/to/page</code> will redirect to <code>https://www.example.com/path/to/page</code>. If disabled, the destination URL will not include the path, such as <code>https://www.example.com</code>.",
      "type": "bool",
      "default": true
    }
  ]
}
```

**script.js**
```
function onStart(server, options) {
    // Do nothing
}

function onRequest(req, res, options, preventDefault) {
    if (typeof preventDefault === 'function') preventDefault();
    res.setHeader('location', options.origin + (options.path ? req.url : ''));
    res.setHeader('content-length', 0);
    res.writeHead(302);
    res.end();
}

module.exports = { onStart, onRequest };
```

@stokito Does this work for your use case?

I'm inclined to close this issue.

**Comment by stokito** [comment]
I'm afraid no one will install any plugin.

**Comment by terreng** [comment]
Is this issue something you actually want to use or for someone else to hypothetically use?

**Comment by stokito** [comment]
https? I think this is something that users will do. So it's not so hypothetically.

**Comment by terreng** [comment]
> I think this is something that users will do.

Are you one of those users?

**Comment by stokito** [comment]
you are too. The github works with https as all web.

**Comment by terreng** [comment]
Let me clarify. Are you someone who wants to use Simple Web Server to host a website on the public facing internet?

**Comment by stokito** [comment]
yes, why not? You see, the problem is that even if it will be 1% of users they will vulnerable without the TLS.

**Comment by terreng** [comment]
Simple Web Server isn't designed to be used for hosting websites on the public internet, and I generally wouldn't recommend it for security reasons.

However, if someone really wants to, I think that creating two web servers and using this plugin to redirect from one to the other is an adequate solution.
