### ISSUE TITLE
ability to refresh page on an interval using HTTP refresh

### ISSUE THREAD

**Issue by MTollens** [terreng/simple-web-server#136]
provide a simple toggle for "Force Refresh" with a seconds interval
my usecase is to display some simple HTML that may get updated in the background on occasion.
giving access to the HTTP refresh flag in some manner would ensure that the page will always be up to date if it has been open for a while.

**Comment by terreng** [comment]
Would #106 solve your problem?

Also, are you aware that it's possible to do this using the HTML meta tag? Like this: `<meta http-equiv="refresh" content="30;URL='https://example.com'" />`

It's also possible to add a custom header using [plugins](https://simplewebserver.org/docs/plugins.html).

**Comment by MTollens** [comment]
yes #106 would satisfy my request, I will look into your other suggestions in the meantime, 
writing a plugin would be my last resort but it is there if I need it
Thank you
