### ISSUE TITLE
Application hanging in Ubuntu 22.04

### ISSUE THREAD

**Issue by xind** [terreng/simple-web-server#138]
**Description/Steps to reproduce**
Please describe what doesn't work and what you expected to happen.
When the "Tray" is enabled in Ubuntu 22.04, the application will not be able to start unless I set it to "false".
And the tray icon is shown btu not working.

**Version information**
Windows, macOS, or Linux?
What version of the program are you using?
NPM version: 9.6.4 or 18.16.0

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Comment by terreng** [comment]
What do you mean by "the tray icon is shown but not working"? I'm confused because you said the application won't start when the trey option is enabled.

**Comment by terreng** [comment]
I've fixed this issue by removing the tray option when running on Linux. The fix is on the `main` branch and I won't do a release for it.
