### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by WebScaffolder** [terreng/simple-web-server#139]
Hi,

When spa parse URL like <script type="text/javascript" src="/js/app.js**?id=e8aacbc4e5e48939f5ba90003d1eadf2**"></script>

shows unexpected token. so my question is script with version no dose not support may  be or is it a bug?

Please let me know...

Thank you.

**Comment by terreng** [comment]
Could you send the error message?

**Comment by WebScaffolder** [comment]
Hi, 

error message was - Unexpected token < when i run SPA.

but when i remove "?id=e8aacbc4e5e48939f5ba90003d1eadf2" from <script type="text/javascript" src="/js/app.js**?id=e8aacbc4e5e48939f5ba90003d1eadf2**"></script>, SPA works.

**Comment by terreng** [comment]
Can you show me the full error message? Please screenshot it.

**Comment by ethanaobrien** [comment]
This sounds like it may be an issue with your code, not with the web server

**Comment by terreng** [comment]
We need the full error message in order to investigate further. Please provide a screenshot.

I'm closing this issue for now, unless we hear back from you.
