### ISSUE TITLE
File system error.

### ISSUE THREAD

**Issue by ShinodaNaoki** [terreng/simple-web-server#140]
![image](https://github.com/terreng/simple-web-server/assets/11781380/49a0499a-f5fb-4859-a530-95277a6104d8)

I got an error when using network drive path. How to solve it?

FYI: It works well when set local drive path. I have installed version 1.2.7 from Microsoft Store.

**Comment by ShinodaNaoki** [comment]
May be this is the log, but I can't read it.
[000003.log](https://github.com/terreng/simple-web-server/files/11633929/000003.log)

**Comment by terreng** [comment]
The logging in the current version of the program isn't detailed enough for us to determine the problem. I just built a new version of the program with more detailed logging.

Please follow these instructions to help us get more details about the problem:

https://github.com/terreng/samples/raw/master/Simple%20Web%20Server%20Installer%201.2.7%20x64.exe

Please download and install this new version. If you aren't comfortable running this file then please let me know and I can provide instructions on how to [build it from the source code yourself](https://simplewebserver.org/docs/build.html) (from the `ja` branch).

To open DevTools to view the logs, please press `CTRL + Shift + I` and switch to the "Console" tab. [Click here for more details.](https://simplewebserver.org/docs/logs.html)

Once you have the logs open, please toggle the web server off and then on again, and share a screenshot of the error message that appears in the console.

Thank you for your help! Please let me know if you have any questions about these instructions or if you get stuck.

**Comment by ShinodaNaoki** [comment]
Thank you!
I'll try it next week, because that occurs on my office network.

**Comment by ShinodaNaoki** [comment]
I have tried the new version, And I got an error, 
`UNKNOWN: unknown error, stat 'V:'`.

And I found that another network drive W: works well, so there are something difference between these two remote PC.

**Comment by terreng** [comment]
Just to confirm, you have selected the entire drive, right? I'm pretty sure that error is outside of our control, unfortunately. You mentioned that a different network drive works. Let us know if you are able to determine the issue.

**Comment by ShinodaNaoki** [comment]
Not only entire drive, but also some underlying folders got the same error.

BTW, Is this help us?
https://stackoverflow.com/a/57962881

**Comment by terreng** [comment]
@ethanaobrien Any thoughts?

**Comment by ShinodaNaoki** [comment]
Is it the difference of remote side file system?
https://github.com/nodejs/node/issues/19965

**Comment by terreng** [comment]
> That 4094 error code is a generic network-or-configuration error, Node.js just passes it on from the operating system.

Confirms that the error is at the OS level. I'm not very familiar with network file systems so I don't think there's much I can do to help, sorry.

**Comment by ethanaobrien** [comment]
Yeah, I was going to say if it worked with one network drive and didn't with another, then it's an os problem, or a configuration error. I wouldn't know

**Comment by ShinodaNaoki** [comment]
I have build self, and found that replacing fs.statSync to fs.statfsSync can avoid first error.
https://nodejs.org/api/fs.html#fsstatfssyncpath-options

But its not enough and browser get a 500/404 error for a folder/file respectivelly.

**Comment by ShinodaNaoki** [comment]
I noticed a difference between the two network drives and want to report it.
Successful drives are on APFS Macs, drives with errors are on Mac OS Extended.
