### ISSUE TITLE
WIndows Hyperv Server

### ISSUE THREAD

**Issue by fullburnscs** [terreng/simple-web-server#145]
Hi, i have a windows hyperv server with gui, and i try select folder but not work, and the program not accept add folder manually.
Maybe you can be add option to add folder manually instead select one.

Thanks.

**Comment by terreng** [comment]
You can manually specify a directory path by [editing config.json](https://simplewebserver.org/docs/config%20file.html). I hope this helps. Please let me know if you are still having trouble.
