### ISSUE TITLE
Add support for serving precompressed .br and .gz files

### ISSUE THREAD

**Issue by andreimilto** [terreng/simple-web-server#146]
It's a common practice to have static resources compressed with Gzip and/or Brotli and stored in the same directory with `.gz`/`.br` extensions respectively:
* `largetext.txt` - uncompressed file
* `largetext.txt.gz` - Gzip-compressed `largetext.txt`
* `largetext.txt.br` - Brotli-compressed `largetext.txt`

When a client requests `largetext.txt`, server checks the `Accept-Encoding` header for supported compression methods:
* if client supports Brotli, server responds with the contents of `largetext.txt.br` and header `Content-Encoding: br`
* client supports Gzip - `largetext.txt.gz` and `Content-Encoding: gzip`
* client supports neither - original `largetext.txt`

It would be great to have Simple Web Server support this scenario. And also to have one or two knobs in the options to switch these on and off to measure bandwidth in cases when different compression algorithms are used or no compression at all.

**Comment by terreng** [comment]
@ethanaobrien I think this would be really easy to implement. Just need to check the accept-encoding header and see if .gz or .br versions of the files exist. Do you think you could do it?

This would just be a single checkbox option that defaults to on. 

> And also to have one or two knobs in the options to switch these on and off

This would be easier to change/experiment with on the client side via the accept-encoding request header, no?

**Comment by ethanaobrien** [comment]
>Just need to check the accept-encoding header and see if .gz or .br versions of the files exist. Do you think you could do it?

Yeah, this would be pretty easy. Just another option.

**Comment by andreimilto** [comment]
> This would be easier to change/experiment with on the client side via the accept-encoding request header, no?

Well, possible - yes, easier - ah, wouldn't really say so😅 
Usually a client is a browser, and these are not very friendly when it comes to exposing compression settings: they are buried deep down, have global scope and require manual editing of a text field. So, having simple switches in the UI at a touch of one's hand would be definitely more comfortable:relaxed:

But I realize that this is probably a niche request. So, maybe it's a good idea to settle for a single toggle for now:

- [ ] Use Precompressed Files


And later, if you decide to add more compression options (e.g., on-the-fly compression with Gzip and Brotli, etc.), then incorporate more fine-grained control over precompressed files as well:

*Gzip Compression*
- [ ] Use Precompressed `.gz` Files (if available)
- [ ] Use On-The-Fly Compression
On-The-Fly Compression Level `[1..9]`
Caching Settings for On-The-Fly Compression:
...

*Brotli Compression*
- [ ] Use Precompressed `.br` Files (if available)
- [ ] Use On-The-Fly Compression
On-The-Fly Compression Level `[1..11]`
Caching Settings for On-The-Fly Compression:
...

**Comment by ethanaobrien** [comment]
>e.g., on-the-fly compression with Gzip and Brotli, etc.

This is already implemented actually, but was deemed too slow for production

**Comment by terreng** [comment]
> Well, possible - yes, easier - ah, wouldn't really say so😅 Usually a client is a browser, and these are not very friendly when it comes to exposing compression settings: they are buried deep down, have global scope and require manual editing of a text field. So, having simple switches in the UI at a touch of one's hand would be definitely more comfortable☺️
> 
> But I realize that this is probably a niche request. So, maybe it's a good idea to settle for a single toggle for now:

I think it's too niche to add, and I think this option belongs on the client side anyway. I found a couple chrome extensions that allow you to modify http request headers [here](https://chrome.google.com/webstore/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) and [here](https://chrome.google.com/webstore/detail/requestly-open-source-htt/mdnleldcmiljblolnjhpnblkcekpdkpa). I'm pretty sure Chrome just added a feature to override http response headers in DevTools, so it wouldn't surprise me if they added a similar feature for request headers in the future.

> See [this](https://github.com/terreng/simple-web-server/blob/f65003ac6381a12482b431a5927757105844c50f/WSC/handlers.js#L861). Technically you can enable it in the config.json manually. It supports `br`, `gzip`, and `deflate` compression

It still works, right? I think I'll add it to the documentation (as a hidden option) just in case anyone still wants to use it.

> Yeah, this would be pretty easy. Just another option.

Do you think you could add it? I suggest the option name be `precompression`.

**Comment by ethanaobrien** [comment]
>It still works, right? I think I'll add it to the documentation (as a hidden option) just in case anyone still wants to use it.

I don't think I've changed anything that would've broken it.

>Do you think you could add it? I suggest the option name be precompression.

Yeah, I can probably add this sometime next week.

**Comment by terreng** [comment]
> Yeah, I can probably add this sometime next week.

Wonderful. We can release 1.2.9 with this and #147.

**Comment by andreimilto** [comment]
> I think it's too niche to add, and I think this option belongs on the client side anyway. I found a couple chrome extensions that allow you to modify http request headers [here](https://chrome.google.com/webstore/detail/modheader-modify-http-hea/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en) and [here](https://chrome.google.com/webstore/detail/requestly-open-source-htt/mdnleldcmiljblolnjhpnblkcekpdkpa).

Agreed, niche it is👐 Thanks for the browser extensions👍

**Comment by terreng** [comment]
@ethanaobrien Do you want to implement this soon? No pressure, just want to know if I should wait to release 1.2.9 so we can include this or not.

**Comment by ethanaobrien** [comment]
Sorry, been a little busy lately. I should be able to implement this before the next release.

What option name are we going to be using for this feature? Once I get that I'll get it implemented right away.

**Comment by terreng** [comment]
How about `precompression`?

**Comment by terreng** [comment]
Landed in 1.2.9.
