### ISSUE TITLE
Basic authentication fails if credentials contain non-ASCII characters

### ISSUE THREAD

**Issue by andreimilto** [terreng/simple-web-server#151]
In the UI input fields `HTTP Basic auth username` and `HTTP Basic auth password` allow users to enter non-ASCII characters: Greek, Cyrillic, Japanese, etc. However, an attempt to pass authentication with such credentials results in `401` error.

The root of the problem is the `atob` function here:

https://github.com/terreng/simple-web-server/blob/0a3648e13c69b0287136d8a473e3a3b22436dd2a/WSC/handlers.js#L278-L285

It uses `ISO 8859-1` encoding to convert an octet sequence into text. Whereas modern browsers default to `UTF-8` encoding for basic auth credentials. Some browsers did use `ISO 8859-1` back in the day, but it was years ago (e.g., Firefox switched to `UTF-8` in [2017](https://bugzilla.mozilla.org/show_bug.cgi?id=1419658)). I've checked mobile and desktop versions of Chrome, Safari, Firefox, Edge, Brave, Vivaldi - they all default to `UTF-8` now.

## Possible Solution 1

Switch to `UTF-8` encoding.
1. Replace `atob` with something like `Buffer.from(base64str, 'base64').toString('utf8')` (note that unlike `atob` it may additionally throw if the octet sequence doesn't represent a valid UTF-8 string)
2. Use the parameter `charset` to explicitly specify the encoding of credentials (eliminate any ambiguity for the client):  
`WWW-Authenticate: Basic realm="foo", charset="UTF-8"`

## Possible Solution 2

Limit the allowed characters in the input fields for the username and password to ASCII-only and continue using `atob`.

**Comment by terreng** [comment]
@ethanaobrien Can I assign this and #153 to you? I think it makes sense to switch to UTF-8 encoding as @andreimilto has helpfully described in solution 1 above.

**Comment by terreng** [comment]
@ethanaobrien Please also merge #148 if it looks good, since that modifies the same lines of code.

**Comment by ethanaobrien** [comment]
>Can I assign this and #153 to you?

Yeah, these should be easy

>I think it makes sense to switch to UTF-8 encoding as @andreimilto has helpfully described in solution 1 above.

Will do

>Please also merge #148 if it looks good, since that modifies the same lines of code.

I'll look at that now

**Comment by terreng** [comment]
Landed in 1.2.9.
