### ISSUE TITLE
Does not recognize PATH_INFO after script.cgi

### ISSUE THREAD

**Issue by paulmsander** [terreng/simple-web-server#165]
**Description/Steps to reproduce**
Create a CGI script named with a .cgi suffix and place it in the document tree.  Load the script's URL and append a slash and PATH_INFO component using the http GET method.  For example:  http://localhost:8080/myscript.cgi/path/parameter

**Version information**
Simple Web Server 1.2.9(27) running on MacOS 13.6

**Screenshots**
No screen shot, but here's a cut-and-paste of the text produced by my site given this URL:  http://localhost:8080/app.cgi/southbay

In this case, app.cgi is a CGI script located in the root directory of my site, and soutbay is a parameter that the script interprets when fetched using the http GET method.

404 - Not Found

Entry Not Found: /app.cgi/southbay

**Comment by terreng** [comment]
Simple Web Server doesn't support running cgi scripts. You're seeing the error because a file doesn't exist at that path.

**Comment by ethanaobrien** [comment]
And adding onto @terreng , I don't believe cgi scripts would be possible, for the same reason php isn't possible
