### ISSUE TITLE
After I set up the server, I selected a nas folder. However, when I went to the web page to view the folder, I could see the files, but I could not download them.

### ISSUE THREAD

**Issue by andy89345** [terreng/simple-web-server#166]
**Description/Steps to reproduce**
Please describe what doesn't work and what you expected to happen.

**Version information**
Windows, macOS, or Linux?
What version of the program are you using?

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Comment by andy89345** [comment]
![image](https://github.com/terreng/simple-web-server/assets/78186288/0f624068-3b7c-4750-a16d-d47ec321a98e)

**Comment by andy89345** [comment]
Like this, When I click the file. I can't download.

**Comment by ethanaobrien** [comment]
Which is expected. You can modify the directory listing and use the htaccess feature to achieve what you'd like.

<https://www.w3schools.com/tags/att_a_download.asp>

**Comment by terreng** [comment]
Just to make sure I'm understanding you correctly, what happens when you click on one of the filenames in that screenshot?

**Comment by terreng** [comment]
It sounds like clicking on the html files renders the pages, which is the expected behavior. You can right click the page and choose "Save As..." (or use the keyboard shortcut Control + S) to save the pages.
