### ISSUE TITLE
Range request out of bounds.

### ISSUE THREAD

**Issue by Jaydee2190** [terreng/simple-web-server#177]
Issue: requesting byte range greater than the content-length of the file.

Let's say a file has a content-range of 815957.  doing a curl -r 0-1048575 "http://simpleserver/file.bin" will return a curl error of 18 and 
Content-Range: bytes 0-1048575/815957
Content-Length: 1048576

This is the amount requested, but more than the length of the file.

Apache http for example will return correctly the maximum amount of the file:
Content-Range: bytes 0-815956/815957
Content-Length: 815957

This line in the code blindly takes the range... without comparing it to the entry.size.. so fileEndOffset I think should be the lessor of entry.size-1 or parseInt(rparts[1])

https://github.com/terreng/simple-web-server/blob/ef693aee1ab8f09ec2995d9ca9f2040404433e79/WSC/handlers.js#L839

**Comment by ethanaobrien** [comment]
Whoops, thanks for the catch

**Comment by terreng** [comment]
Will be fixed soon in 1.2.14. Thanks!
