### ISSUE TITLE
Test for permission to serve directories

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#18]
- [x] Detect if we don't have permission to read a file or directory at runtime, and serve a 403 error
- [x] Don't serve files outside of selected path (don't allow for /../ in url)

**Comment by ethanaobrien** [comment]
With the way I built the filesystem, it always combines the input path and the base path. Should we just add an error for when user requests something like 
http://localhost:8887/../../somepath

**Comment by ethanaobrien** [comment]
They shouldn't be able to select a directory that they don't have read
access from, because they need read access to be able to go in and select
it. The web server is also run with the same privileges so the server would
get an unauthorized error. Should I try to handle this error? Is there more
to this that I am missing?

**Comment by terreng** [comment]
Does Windows already prevent you from picking a directory you don't have access to?
Does the web server already handle read permission by returning a 403?

**Comment by ethanaobrien** [comment]
Windows does not block selecting the directory, but blocks reading it. The server does not check for read permissions

**Comment by terreng** [comment]
What happens when the server tries to serve a file it doesn't have permission to read?

**Comment by ethanaobrien** [comment]
Fs returns an error and then renders the 404 page

**Comment by terreng** [comment]
Could we add a case for a fs permission error and make that a 403 instead?

**Comment by ethanaobrien** [comment]
Possibly, I'll take a look at that when I get a chance
