### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by vespina** [terreng/simple-web-server#183]
Modified lang.js to add spanish language.
[lang..txt](https://github.com/terreng/simple-web-server/files/14203017/lang.txt)

**Comment by terreng** [comment]
Thank you so much for your work translating for us, it's super helpful and very much appreciated! I'm going to try and release this in an update tomorrow.

**Comment by vespina** [comment]
My pleasure. I liked very much your app.  Simple and useful.

**Comment by terreng** [comment]
Thank you! I'm going to add your GitHub username to the bottom of the website homepage as a thank you for providing the translation.

**Comment by vespina** [comment]
> Thank you so much for your work translating for us, it's super helpful and very much appreciated! I'm going to try and release this in an update tomorrow.

BTW, I also submitted an spanish translation for the main readme.md in the "Help us translate" issue (#124).

**Comment by terreng** [comment]
I saw that, thanks! We just released version 1.2.10 which includes your Spanish translations.
