### ISSUE TITLE
IPAddress on the main view

### ISSUE THREAD

**Issue by vespina** [terreng/simple-web-server#185]
It would be nice and helpful to show the current IP address which the servers will be responding to, specially when your computer is configured to use dynamic IP addresses.  Right now every time I activate the server I have to go to the Network preferences to check what the current IP address is so I can enter the right url on the other computers.

**Comment by ethanaobrien** [comment]
While the server is running, you should be able to click the server and see these addresses in the settings menu
![image](https://github.com/terreng/simple-web-server/assets/77750390/794d2831-e9d6-4cbc-b562-1a7adaf8f427)

**Comment by vespina** [comment]
NIce. That will do it.
