### ISSUE TITLE
PUT request causes Internal Server error

### ISSUE THREAD

**Issue by wadekburg** [terreng/simple-web-server#189]
I try to use Simple Web Server on macOS Big Sur 11.7.10
PUT request causes Internal Server error.
In server log:
[3/23/2024, 12:50:56 PM] 127.0.0.1: Request PUT /Test.bin
Error writing file {
  "errno": -1,
  "code": "EPERM",
  "syscall": "open",
  "path": "/Users/andrejkuchkin/httproot/Test.bin"
}

**Comment by terreng** [comment]
Did you download from the website or the Mac App Stone?

@ethanaobrien thoughts?

**Comment by wad1966** [comment]
I downloaded this program from the app store

**Comment by terreng** [comment]
Can you try downloading from our website and trying the exact same thing again?

**Comment by wad1966** [comment]
ok, thanks, I'll try and post the result.

**Comment by ethanaobrien** [comment]
> @ethanaobrien thoughts?

No clue, as long as the user has write permission it should work, though it might just be macOS being picky for some reason

**Comment by wadekburg** [comment]
I downloaded it form gihub directly and it works correctly now! But, where is servers's config.json, etc. now?

**Comment by wadekburg** [comment]
That's it, figured it out! Thanks to everyone!

**Comment by terreng** [comment]
Glad to hear it!
