### ISSUE TITLE
Legacy-Compatibility back again?

### ISSUE THREAD

**Issue by PARAViRTUALiZATiON** [terreng/simple-web-server#190]
* It seems that this was the latest Version with Windows⁷-Compatibility

**https://github.com/terreng/simple-web-server/releases/tag/v1.2.8**

**Comment by ethanaobrien** [comment]
I don't see a need to support an operating system that hasn't had security updates in years

**Comment by terreng** [comment]
Sorry, we can't support Windows 7 going forward. Our program was built with Electron, with no longer supports Windows 7. You are welcome to continue using the latest compatible version, not much has changed since then anyway.
