### ISSUE TITLE
Single page rewrite should ignore query string

### ISSUE THREAD

**Issue by msssk** [terreng/simple-web-server#194]
**Description/Steps to reproduce**
* Enable "Single page rewrite"
* expect request for existing file `/path/file.html` to load the requested file
  * ✔ works as expected, `file.html` is loaded
* expect request for existing file `/path/file.html?key=val` to load the requested file
  * ❌ does not work, `index.html` is loaded

**Version information**
Windows
What version of the program are you using?
1.2.10

**Comment by ethanaobrien** [comment]
Interesting how the regex catches this. Technically related to #88 which allows changing the matching regex based on your needs

**Comment by terreng** [comment]
I'm not sure if we've implemented this the right way. Right now if you try to access a "valid file path" like `/asdf.html`, it'll return a 404. I think this should instead return `index.html`. I think it should always return `index.html` unless the path is a valid file. Thus it should be impossible to see a 404.

@ethanaobrien Does that make sense / seem right? If so we wouldn't need regex at all... We could use the javascript `URL` constructor get just the pathname part of the url and ignore the query string. Could you implement this?

**Comment by ethanaobrien** [comment]
That would work, yes

**Comment by terreng** [comment]
We could close #88 then too.

**Comment by terreng** [comment]
Will be fixed soon in 1.2.14. Thanks!
