### ISSUE TITLE
Consistent response error format

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#22]
I think we should use the following standard format for http errors:

Error 404: Not Found
Error 403: Forbidden
Error 500: Internal Server Error

etc.

**Comment by ethanaobrien** [comment]
I don't quite get what you mean. Isnt this what I have?

**Comment by terreng** [comment]
When http errors are returned in the code, they aren't consistently formatted. for example:
```js
if (origdata[i].type == 403 && origdata[i].request_path == filerequested) {
    this.error('<h1>403 - Forbidden</h1>', 403)
    return
}
if ((origdata[i].request_path == filerequested && origdata[i].type == 'POSTkey') ||
    (origdata[i].request_path == filerequested && origdata[i].type == 'serverSideJavaScript')) {
    this.error('bad request', 403)
    return
}
```

**Comment by ethanaobrien** [comment]
@terreng Yikes! Thanks for pointing that out
