### ISSUE TITLE
Start SWS as a service on Windows Server

### ISSUE THREAD

**Issue by ntskalman** [terreng/simple-web-server#220]
I'm trying to start Simple Web Server as a service on a Windows Server 2016 by creating a service like this:

New-Service -Name "SimpleWebServer" -DisplayName "Simple Web Server" -Description "Simple Web Server" -StartupType Auto -BinaryPathName "C:\Users\<username>\AppData\Local\Programs\simple-web-server\Simple Web Server.exe --service"

The service gets created fine, but when I try to start the service, I get the following error:

The Simple Web Server service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.

What am I doing wrong? Or can it not be started as a service?

**Comment by terreng** [comment]
@ethanaobrien Do you understand this at all?

This is just an Electron thing afaik. If it doesn't work it doesn't work.

**Comment by ntskalman** [comment]
I've just solved it by uninstalling and replaced it by an apache server.

**Comment by ntskalman** [comment]
I've just solved it by uninstalling and replaced it by an apache server.

**Comment by ethanaobrien** [comment]
> @ethanaobrien Do you understand this at all?


I dont, I haven't used windows in months now so I don't have an easy way to test either. This is like an electron thing or the requirement of a gui

**Comment by ntskalman** [comment]
The normal and easy way to make an application start as a Service in Windows is to create a Service with Powershell:

New-Service -Name "SimpleWebServer" -DisplayName "Simple Web Server" -Description "Simple Web Server" -StartupType Auto -BinaryPathName "C:\Users\<username>\AppData\Local\Programs\simple-web-server\Simple Web Server.exe --service"

After that you only have to start the service - but it returns the error:

"The Simple Web Server service failed to start due to the following error:
The service did not respond to the start or control request in a timely fashion."

I choose another solution in this case by installing Apache for Windows. The only reason for using Windows in this case is that I have a Windows application that runs a diagnostic and security check and generates an HTML report that I want to host internally on a website.

**Comment by terreng** [comment]
Thanks for explaining that more. I'll close this again since our program probably isn't a good choice for this particular use case, and neither of us know how to fix it. Thanks!
