### ISSUE TITLE
Name & Logo

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#3]
Here's the current name and logo:
![image](https://user-images.githubusercontent.com/11605395/126580527-d31be4b2-4677-425c-9f1a-f667e578e87d.png)

kzahel gave us permission to use the web server for chrome logo:
![image](https://user-images.githubusercontent.com/11605395/126580583-cd3a741f-2bbe-4338-b4ad-9242bde265f9.png)

Do we want to use the web server for chrome logo or a new logo?
I could also make an updated version of the web server for chrome logo to make it look better while keeping its charm.
Let me know what you think @ethanaobrien.

Also, what should we call this? 
It doesn't make sense to use the old "Web Server for Chrome" name because it isn't a chrome app anymore.
I like the name "Simple Web Server". Do you have any other ideas?

**Comment by ethanaobrien** [comment]
@terreng In my opinion, I really really like the old web server for chrome logo so here is what I propose.

We use the old logo with the new name "Simple Web Server"

I feel like we need something connecting the 2 things

**Comment by terreng** [comment]
Okay, so we should use the old logo and go with the name Simple Web Server?

How will people discover the app? I know we'll add a thing to web server for chrome telling people about it. Do you think it makes sense to also set up a website or spread the word about it some other ways?

**Comment by ethanaobrien** [comment]
> Okay, so we should use the old logo and go with the name Simple Web Server?

Yes, I think this is how we should do it.

>How will people discover the app? I know we'll add a thing to web server for chrome telling people about it. Do you think it makes sense to also set up a website or spread the word about it some other ways?

Yeah, I think that is a good idea, Doesn't electron have a place where you can upload an app, or am I wrong?
We could use github.io to host a how to and register it in the google search indexer.

**Comment by terreng** [comment]
I'm not so sure that it's accurate to call our app "Simple" if we are going to add so many options.

**Comment by ethanaobrien** [comment]
That's a really good point, especially with my server side JavaScript and htaccess options. Any ideas?

**Comment by terreng** [comment]
I think we can keep the name "Simple Web Server" because even though it has a lot of features, the basics are still very simple, and it does everything it can to make the more advanced features simple too. It's a lot more simple than it would be to setup an Apache server for example.

So I say we go with "Simple Web Server". After all, that's probably what most people would Google search when they're looking for something like this, right?

**Comment by ethanaobrien** [comment]
Yeah, I agree

**Comment by ethanaobrien** [comment]
Also, I got an email saying that you removed unused dependencies. Which modules did you remove?

**Comment by terreng** [comment]
`net` and `url` don't need to be installed because they're part of node, so I removed them from package.json

**Comment by ethanaobrien** [comment]
Oh, I didn't know that. Cool

**Comment by terreng** [comment]
I just renamed this repo to `simple-web-server`.

**Comment by ethanaobrien** [comment]
Awesome, should this be closed?

**Comment by terreng** [comment]
Not yet, I still need to update the logo

**Comment by ethanaobrien** [comment]
Any progress on the tray icon?

**Comment by terreng** [comment]
I'm probably going wait to work on the tray until after the first release.

**Comment by terreng** [comment]
Seeing as we've decided both a name and a logo, I'm going to close this issue.

**Windows & Linux**
![icon](https://user-images.githubusercontent.com/11605395/140629704-fd8feeba-ea18-4d54-bf2d-9989f94524c0.png)

**macOS**
![macosicon](https://user-images.githubusercontent.com/11605395/140629709-32b88624-5bab-4945-92a7-ba3e9ba4e6c0.png)

**Comment by ethanaobrien** [comment]
I really like that, cool
