### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#4]
Single page website design. Menu on left. Sandwich icon on mobile.

Mention not available on Chrome OS. Mention continuation of Web Server for Chrome.

- [x] Remember site meta tags

Home -> GitHub link, Screenshots and description
Download -> Download links, install instructions, changelog, link to build from source docs
Documentation
&bull; Server Options
&bull; App Settings
&bull; Specific feature docs

- [x] TODO: Favicon

**Comment by ethanaobrien** [comment]
@terreng Whats this for?

**Comment by terreng** [comment]
I'm going to build a website for our app. It'll have a description of what it does and screenshots, a download button, and it'll have all of our documentation.

**Comment by ethanaobrien** [comment]
@terreng Sounds Awesome!

I had an idea that for opening the readme's (the htaccess/post/ipblocking) to use the window.open method (From the window) and open an html with the readme, this way there will be no required internet access (In case github is blocked or internet is down)

**Comment by terreng** [comment]
I'm going to include an explanation for all the options that you'll be able to view by clicking a question mark icon next to each option. Some of the options require longer explanations, so they will link to one of the readmes. I'm actually going to include them using an iframe, but its very similar to what you described.

We should have documentation explaining what all of the options do, what their valid values are, and linking to longer explanations if necessary.

**Comment by terreng** [comment]
We now have https://simplewebserver.org

**Comment by ethanaobrien** [comment]
that is awesome!

**Comment by terreng** [comment]
@ethanaobrien The website is coming along. Take a look at the documentation section and let me know what you think. https://simplewebserver.org/

**Comment by ethanaobrien** [comment]
Wow I love the look. It's really clean. Keep doing what youre doing it looks good!

**Comment by terreng** [comment]
@ethanaobrien Please see [Coming from Web Server for Chrome?](https://simplewebserver.org/docs/wsc) and let me know if you have any thoughts.

**Comment by ethanaobrien** [comment]
>Thanks for the suggestion. I didn't realize this was possible without any changes to the app. Could you link to a good article about how to do it?

I think [this](https://www.hellotech.com/guide/for/how-to-port-forward) is a pretty good guide, walks you through pretty thoroughly.

>Do you want to add IPV6 support in a pr that closes https://github.com/terreng/simple-web-server/issues/80? Let's call the boolean option ipv6. Update getIPs() to include both ipv4 and ipv6, and in the UI I'll add code to filter the list of ips based on the ipv6 option.

Yes, would you like me to have each url as an object with the properties `isIpv4` (true or false) and `address` (the text) or do you just want me to push everything as a string and you have the detection?
Also make sure you follow the instructions [here](https://superuser.com/a/367788/1247939) to format the ipv6 address properly

>I actually already added a favicon yesterday. You might just need to refresh the page/clear cache.

I just looked at the source and realized the problem. I think icons need to be in the `.ico` file format. I see the tag but my browser does not load the icon

**Comment by terreng** [comment]
> I think [this](https://www.hellotech.com/guide/for/how-to-port-forward) is a pretty good guide, walks you through pretty thoroughly.

Thanks for linking that. I'll update the documentation accordingly.

> Yes, would you like me to have each url as an object with the properties isIpv4 (true or false) and address (the text) or do you just want me to push everything as a string and you have the detection?

My first thought was to just filter based on the ips themselves, but I think your suggestion is a better idea. Let's have `getIPs()` return an array of address and type pairs, like so: `[["1270.0.1","ipv4"],["1080::8:800:200c:417a","ipv6"]]`

I will have to update the interval on line 230 of index.js and the UI code in order to support this change. It might break things for now once you make the change.

Thanks for the details about formatting ipv6, that's super helpful. I'll make sure to follow that.

> I think icons need to be in the .ico file format. I see the tag but my browser does not load the icon

Yes, I've already added the favicon at `/favicon.ico`. I think favicons can be pretty aggressively cached. Just open DevTools, right click on the refresh option, and choose empty cache and hard reload.
<img width="398" alt="Screen Shot 2022-04-05 at 11 35 54 AM" src="https://user-images.githubusercontent.com/11605395/161791479-35502970-4c87-4366-ad5a-cc3b47abbf12.png">

**Comment by ethanaobrien** [comment]
I just opened a pr. 

>Yes, I've already added the favicon at /favicon.ico. I think favicons can be pretty aggressively cached. Just open DevTools, right click on the refresh option, and choose empty cache and hard reload.

Found it. You are setting the rel to `shortcut icon`. As [this comment](https://stackoverflow.com/questions/25952907/what-is-the-best-practice-for-creating-a-favicon-on-a-web-site#comment66114603_25961390) states this is only technically supported in ie. Not sure why it is loading for you as nothing seems to be working for me, even when I do the steps you provided

**Comment by terreng** [comment]
> Not sure why it is loading for you as nothing seems to be working for me, even when I do the steps you provided

I can assure you that I have set up the favicon properly.

**Comment by ethanaobrien** [comment]
You saw the part of my comment where I said the method you are using to set the favicon is only supported on IE right?

**Comment by terreng** [comment]
Please believe me that I know what I'm doing. `<link rel="shortcut icon" href="/favicon.ico">` is supported in all browsers. You might still not be seeing it because of caching.

**Comment by ethanaobrien** [comment]
([see this](https://mathiasbynens.be/notes/rel-shortcut-icon))

I am trying on a completely different computer that has never loaded the site and still nothing

**Comment by terreng** [comment]
> ([see this](https://mathiasbynens.be/notes/rel-shortcut-icon))

It might interest you to know that YouTube and Twitter both use `rel="shortcut icon"`. If you don't believe me, you can go to either site and view page source for yourself.

Just because something isn't in the spec doesn't mean it's not widely supported/used. Browsers tend to have good backwards compatibility for things like this.

Take the `<center>` tag for example. This tag was deprecated with the release of HTML 4 clear back in 1998. Despite this, it's still supported in every browser, because there's no reason to remove support for it. (And every reason not to.)

I understand that the official, to the spec way of specifying a favicon might differ from what I've done. But it doesn't matter. I think this is important to understand.

> I am trying on a completely different computer that has never loaded the site and still nothing

In addition to the meta tag, I've played the favicon at root, which is very standard and widely supported. I genuinely do not know why this would not be working for you.

**Comment by ethanaobrien** [comment]
Hey @terreng I have a quick question not relating to the development of this project. What service do you use to host the website itself? Do you use something like netlify or heroku or something else entirely?

**Comment by terreng** [comment]
I'm using Cloudflare Pages to host the website. It's static hosting but it supports running a build script first. Pretty sure GitHub Pages can do that now too.

When all you need is basic static hosting, options like Cloudflare Pages, GitHub Pages, or Firebase Hosting are good (among others I'm sure). Static hosting means it's just serving a set list of files / directories.

Heroku isn't the best choice for this because you don't need a full web server (custom web server code) just for static hosting. If you wanted to do something more advanced like generate pages on the server from a database, then you'd need to be able to actually run code in response to http requests. This is what Heroku, App Engine, etc. are designed for.

Let me know if you have any other questions about hosting.

**Comment by ethanaobrien** [comment]
Nope, that's all the information I needed. Thank you!
