### ISSUE TITLE
HTTPS documentation

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#43]
@ethanaobrien Could you please create some basic documentation on how to set up the HTTPS feature for someone who has never used it before? 

Here's a screenshot of what the UI looks like currently.
<img width="417" alt="Screen Shot 2021-12-30 at 5 23 47 PM" src="https://user-images.githubusercontent.com/11605395/147797640-fafc910e-be50-42c2-a445-c90e4ad5700e.png">

Do the auto-generated certs also work on the local network or just localhost?

**Comment by ethanaobrien** [comment]
>Do the auto-generated certs also work on the local network or just localhost?

They work on the local network and localhost. Although, since it will say it is not secure because it is a self signed certificate.

Do you want me to comment with the documentation or attempt to put it into the UI?

**Comment by terreng** [comment]
If you could create a pr to add the documentation as a file, that would be great.

**Comment by terreng** [comment]
> Also, you might want to hide the certificate and private key options when the user does not have the https option on (It makes it look a lot cleaner)

Thanks for the suggestion. I tried it out, but I think I'll leave the cert and key visible even when https is unchecked. I think people might want to change the cert even while https is currently off. I don't think there are enough options in that section for it to look cluttered. So I'll leave it as is, but let me know if you still think I should change it.
