### ISSUE TITLE
entry not found 

### ISSUE THREAD

**Issue by WebScaffolder** [terreng/simple-web-server#48]
Hi,

entry not found - after build GitHub source  again with latest source v1.0.1 has no problem but WSC missing from source. Can i have latest stable full source please with WSC so that do some testing with handlers PUT method as it is showing CORS error problem?

**Comment by ethanaobrien** [comment]
The only copy I have of a stable release is found here
https://drive.google.com/drive/folders/1MmJYRceI1g1ZLNvANZ3AlnG9KB8GF3_h
I only have it built for windows (use the `.zip` file)

**Comment by terreng** [comment]
The latest source is on the [new-ui branch](https://github.com/terreng/simple-web-server/tree/new-ui). Try building from that.

**Comment by WebScaffolder** [comment]
Hi terreng,

i had build from new ui but still showing entry not found: /login even after new build or npm start but stable source works fine where WSC folder has been packed. please let me know as still PUT needs OPTION I think.

**Comment by terreng** [comment]
This issue is related to #47, let's keep the conversation there.
