### ISSUE TITLE
Auto-updater

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#5]
Make this optional, and ask when first opened before making any network requests.

Add an option to settings "Check for updates"

Show a banner when updates are available. Check a file at simplewebserver.org/versions.json

**Comment by terreng** [comment]
@ethanaobrien Instead of building an auto updater into the program, I think we should instead just check if there is a new version available, and make the user go and download the new version to update. We should make sure the installer replaces an old version if it's already installed. The Windows / macOS store will already take care of automatic updates for us. So we would only have the update checker built in to the manual install version. How does this sound?

**Comment by ethanaobrien** [comment]
Yes, I agree. I think we should only do this on the manual install version. Are we going to do an exe release that installs to appdata or programdata?

**Comment by terreng** [comment]
Haven't you already figured out how to make a windows installer? AppData is only for storage files, we should definitely not install program files there.

**Comment by ethanaobrien** [comment]
Sorry, I meant Program Files. I have figured out how to make one that will publish to the windows store.

**Comment by terreng** [comment]
I forgot that we'd need a separate apple developer account for the macOS App Store. Nevermind about that.

App data local or roaming?

**Comment by ethanaobrien** [comment]
`local`. electron stores the save data in the `roaming` folder and the app in the `local` folder

**Comment by terreng** [comment]
Okay, makes sense, that sounds good.

**Comment by terreng** [comment]
There is room for future improvement here, with code signing. But I'm closing for now.
