### ISSUE TITLE
suddenly not working and shows directory listing only.

### ISSUE THREAD

**Issue by WebScaffolder** [terreng/simple-web-server#50]
![sudden death](https://user-images.githubusercontent.com/48052351/150411345-2860d54e-c143-40a9-b993-ffffb4518660.gif)

Hi,

Simple web server suddenly not working and shows directory listing instead. Please have a look.

**Comment by terreng** [comment]
Could you please confirm that the option to automatically show index.html is enabled?

**Comment by WebScaffolder** [comment]
Hi, it doesn't matter automatically show index.html turned on or off.

**Comment by terreng** [comment]
@ethanaobrien Could you please take a look at this? Notice how the directory listing page says "Index of /index.html/"

**Comment by ethanaobrien** [comment]
@terreng 
Yep I see that. I'll take a look

**Comment by WebScaffolder** [comment]
just found if i create **"index": true** on C:\Users\xxx\AppData\Roaming\Simple Web Server\config.js it works. but still do not know i did solve - i did this as i found below

function alldone(results) {
                    if (**this.app.opts.index**) {

**Comment by ethanaobrien** [comment]
I found the bug, give me a second

**Comment by WebScaffolder** [comment]
OK

**Comment by terreng** [comment]
@WebScaffolder Thanks for your help in finding these bugs, we really appreciate it.
