### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#54]
Put all copy into a language file to make translating to more languages easy. Translate website and documentation.

**Comment by antnesswcm** [comment]
I want to use Chinese, how should I set it up. Or translate and adapt it yourself

**Comment by terreng** [comment]
If we sent you a language file in English, would you be willing to translate it to Chinese for us? If you do, we could add Chinese to the app.

**Comment by antnesswcm** [comment]
Yes, I can  ,Related files can be sent to antnesswcm@ gmail.com

**Comment by antnesswcm** [comment]
I'm waiting for your reply Thank you

**Comment by terreng** [comment]
Thanks for your patience. I'm working on preparing language files for you to translate, because I didn't have it ready yet. Can you translate to Simplified Chinese or Traditional Chinese?

**Comment by antnesswcm** [comment]
There is no problem with Chinese translation. I don't use traditional Chinese in Chinese Mainland, but I can try

**Comment by terreng** [comment]
If you don't use Traditional Chinese then you can only translate to Simplified Chinese, which is not a problem!

Here is the file to translate to Simplified Chinese:
[language_strings.json](https://github.com/terreng/samples/blob/master/language_strings.json)

This is a JSON file. Please let me know if you have any questions about the file format. Let me know if a different file format would be easier for you to use.

Please let me know if you have any questions about what anything means.

Thank you for your help translating!

**Comment by antnesswcm** [comment]
## Translation is basically completed

But there is one place, I don’t understand and I can’t guess, because I never use this function
### at “Advanced Rules”
```
Optionally specify a custom string that will be looked for in your error pages and replaced with the current path.
if your custom 404 page included: The file at {{PATH}} does not exist and you set this option to {{PATH}}, when your custom page is served it would say The file at /example.txt does not exist.
```
I hope you can help me

**Comment by terreng** [comment]
Thanks for your help!

Thanks for about what the "Custom error path variable" option does. The default 404 error page looks like this:

<img width="355" alt="Screenshot 2023-02-16 at 10 35 57 AM" src="https://user-images.githubusercontent.com/11605395/219413244-06ea2590-35fb-4e7c-b545-7be9a99011c5.png">

It shows the name of the file that you tried to visit.

The "Custom 404 page file path" option allows you to make a custom error page. You can make it look however you want. However, because the page is a static file, it wouldn't be able to show the name of the file like the default error page does.

To solve this problem, the "Custom error path variable" option allows users to choose text in their custom error page that will be replaced with the file path. For example, if you set the option to "{{PATH}}" and your custom error page looked like this:

```html
<html>
  <head>
    <title>404 Not Found</title>
  </head>
  <body>
    The file at {{PATH}} was not found.
  </body>
</html>
```

Then, when the app used the custom error page, it would replace `{{PATH}}` with the actual file path. So the actual page would look like this:

```html
<html>
  <head>
    <title>404 Not Found</title>
  </head>
  <body>
    The file at /example.html was not found.
  </body>
</html>
```

I hope this helps explain what the option does! Thanks for asking.

You can upload the translated file here to GitHub. For some reason, GitHub doesn't allow uploading JSON files. You can just rename the file to .txt and it will work.

If you would rather send the file over email, you can email it to [terren@simplewebserver.org](mailto:terren@simplewebserver.org).

**Comment by antnesswcm** [comment]
## Finished

[language_strings-chinese.json.txt](https://github.com/terreng/simple-web-server/files/10758335/language_strings-chinese.json.txt)

I am very happy to contribute to the cause of open source

**Comment by terreng** [comment]
Thanks so much! We're really excited to be able to make the program available in Chinese in the next update.

I noticed that a few things weren't translated, such as "Rewrite to (for SPAs)" and "Set CORS headers". I just wanted to make sure, was this on purpose or an accident?

Could you also translate our App Store description?

```
Create local web servers in just a few clicks with an easy-to-use interface.

Easy to configure
Change server options with just a few clicks.

Run multiple & in the background
Run multiple web servers at the same time, even when the app is closed.

Single Page Applications
Enable mod rewrite for SPAs with a single click.
```

**Comment by antnesswcm** [comment]
I look forward to the update of the Chinese version.😁

[language_strings-chinese.json.txt](https://github.com/terreng/simple-web-server/files/10763435/language_strings-chinese.json.txt)
I added the translation of "Rewrite to (for SPAs)" and "Set CORS headers"

At first, I felt that the effect after translation was not ideal, because the professional terms were expressed more accurately in English, and those who could use this function should have no obstacles to understand, but I still translated in this file and kept some English to avoid confusion. Now the page looks more unified and harmonious


The app store description has also been translated：
```
简单易用! 只需几次点击就可以部署本地 Web 服务器。

配置超简单
通过图形界面即可更改服务器配置。

多个服务 & 静默运行
即使关闭了应用程序，也可以在后台同时运行多个Web服务器。

单页应用程序(SPA)
一键启用SPA的重写模式。不用担心细节实现!
```

**Comment by terreng** [comment]
@antnesswcm Thank you very much for your contribution!! Version 1.2.5 adds Chinese and is now released! (Released on the website and Mac App Store, will be updated on the Microsoft Store soon)
