### ISSUE TITLE
IP changing

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#55]
What happens if the local network IP changes while the program is running? This should trigger an event to restart the servers and send a message to the UI with the new IP.

**Comment by ethanaobrien** [comment]
@terreng When do you need this done by?

**Comment by terreng** [comment]
> @terreng When do you need this done by?

I think we should have this done for the initial release

**Comment by terreng** [comment]
The UI now updates when the ip changes. I've changed the interval to be every 5 seconds because I can't find a reason why this would be a problem.
