### ISSUE TITLE
Accessible on internet / Port mapping

### ISSUE THREAD

**Issue by ethanaobrien** [terreng/simple-web-server#56]
Ability to route through the router and make available on the internet (via your ip) chrome web server supports this

**Comment by terreng** [comment]
@ethanaobrien What would this option do that isn't already possible by port forwarding?

**Comment by ethanaobrien** [comment]
Yes, Id like to make it to where the server does the port forwarding for you

**Comment by terreng** [comment]
Could you help me understand how that would work?

**Comment by ethanaobrien** [comment]
Most likely we would find a command line exe that we can run it with certain arguments and it will map the port (we would run it from the javascript)

**Comment by terreng** [comment]
Are you saying its possible to map the port without making changes to router configuration?

**Comment by ethanaobrien** [comment]
no, not technically without making changes, but it is possible without having to manually make changes

**Comment by terreng** [comment]
Okay, so this option would make the changes to your router for you?

**Comment by ethanaobrien** [comment]
correct

**Comment by terreng** [comment]
What did the "also on the Internet" option in Web Server for Chrome do?

**Comment by ethanaobrien** [comment]
It automatically opened a port on the router

**Comment by terreng** [comment]
How?

**Comment by ethanaobrien** [comment]
I dont completely know yet. Ive looked at it but havent tried to replicate it. You can take a look [here](https://github.com/kzahel/web-server-chrome/blob/master/upnp.js)

**Comment by terreng** [comment]
The more I've thought about it, the more I think this isn't a good idea. This web server clearly isn't designed to be used on actual websites, and opening it up to the internet presents a security concern. I think if someone really wants to do this, then they can set up port forwarding through their router manually. I don't think we should add this as an option.

**Comment by ethanaobrien** [comment]
Thats understandable and I dont have a problem with this. Do you want to close this or do you think we could have a security warning when enabling? (Sorry I havent been as active the last few weeks, I dont know when I might be more active)

**Comment by terreng** [comment]
Let's not provide it as an option, and assume that anyone who sets it up themselves knows what they're doing. So I'll close this issue.
