### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#59]
I'm getting a blank page at `/` with this combination of options.

<img width="427" alt="Screen Shot 2022-01-23 at 4 22 30 PM" src="https://user-images.githubusercontent.com/11605395/150698495-2f45f306-d5cd-4eff-9364-8c76b9b905d5.png">

<img width="768" alt="Screen Shot 2022-01-23 at 4 23 05 PM" src="https://user-images.githubusercontent.com/11605395/150698510-bc85b586-82a9-4b99-b750-b032786d988a.png">

<img width="768" alt="Screen Shot 2022-01-23 at 4 23 12 PM" src="https://user-images.githubusercontent.com/11605395/150698511-1790bc91-3f54-4245-b6a7-5460a61f59ec.png">

**Comment by ethanaobrien** [comment]
@terreng I just tested, this is not occurring for me

**Comment by terreng** [comment]
The status code is 301 Moved Permanently.

**Comment by ethanaobrien** [comment]
Is there a `location` header? Can you comment with the headers you get when this occurs. You can open inspect, go to network, and click on the request. There will be a field that says response headers, click view raw and could you copy and paste the headers here? Thanks!

**Comment by terreng** [comment]
I'm doing more testing and getting stranger results.

When I turn off all of the options in the basic rules section, nothing loads. It hangs for a long time, and sometimes I get a refused to connect error. However, if I try to access a url for a file that does not exist, I get a not found error just fine. Even though the option is turned off, I get a directory listing at `/`.

When I turn on auto show index, SPA rewrite to /index.html, and show directory listing, I get the same issue. Nothing loads. However this time, even though directory listing is now on, I get a blank page at `/` as I've described. `location` response header is there but blank.

<img width="335" alt="Screen Shot 2022-03-15 at 8 24 44 PM" src="https://user-images.githubusercontent.com/11605395/158493359-5f5f3170-693f-44f9-82ea-f9bc81652f3e.png">

**Comment by ethanaobrien** [comment]
Thank you, Ill do some more digging when I can

**Comment by ethanaobrien** [comment]
@terreng The directory listing is a bug. Ill fix

The problem is you removed send, in the console when trying to render I get the error

```
(node:22824) UnhandledPromiseRejectionWarning: ReferenceError: send is not defined
    at DirectoryEntryHandler.readyToSend (C:\Users\Ethan\git\simple-web-server\WSC\handlers.js:1176:13)
    at DirectoryEntryHandler.writeHeaders (C:\Users\Ethan\git\simple-web-server\WSC\handlers.js:128:13)
    at DirectoryEntryHandler.renderFileContents (C:\Users\Ethan\git\simple-web-server\WSC\handlers.js:1186:18)
    at DirectoryEntryHandler.excludedothtmlcheck (C:\Users\Ethan\git\simple-web-server\WSC\handlers.js:698:22)
    at DirectoryEntryHandler.htaccessCheck2 (C:\Users\Ethan\git\simple-web-server\WSC\handlers.js:1063:59)
    at DirectoryEntryHandler.htaccessMain (C:\Users\Ethan\git\simple-web-server\WSC\handlers.js:1098:50)
    at DirectoryEntryHandler.onEntry (C:\Users\Ethan\git\simple-web-server\WSC\handlers.js:1155:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I added this to my pr

The reason the directory listing was rendering was because in the original web server chrome, the auto render index option was required to disable the directory listing, I have changed this.


Also, I've been thinking. If we are going to re-write this into another language I think we should continue to maintain the electron version. Re-writing it would completely get rid of the server side anything permanently.

**Comment by terreng** [comment]
@ethanaobrien Great! Thanks for figuring out the problems. I didn't realize we were still using send.

It looks like we're only using send in one place. Do you think you could WSC code to read and serve files instead? That way we could get rid of the send dependency. 

> Re-writing it would completely get rid of the server side anything permanently.

I'm not quite sure what you mean by this. Could you clarify? Thanks.

**Comment by ethanaobrien** [comment]
>It looks like we're only using send in one place. Do you think you could use your WSC code to read and serve files instead? That way we could get rid of the send dependency.

I plan to, I've been looking into this. Might be a while before its done though (sorry) but I'll work on this when its time)


>I'm not quite sure what you mean by this. Could you clarify? Thanks.

We are able to have things like server side javascript, since javascript is compiled on runtime this allows us to do this. Most other languages dont do this.

**Comment by terreng** [comment]
> We are able to have things like server side javascript, since javascript is compiled on runtime this allows us to do this. Most other languages dont do this.

Ohh. I didn't even think about that. I'm pretty sure it would still be possible though! We could have the JavaScript run inside the webview. It just means that when you enable that feature, your background memory usage would increase a little bit because the webview would have to be kept loaded. Not a big deal though, still a lot better than Electron.

**Comment by ethanaobrien** [comment]
Ok, awesome!

**Comment by terreng** [comment]
@ethanaobrien This is mostly fixed, but the original issue is actually still present.

I have the single page rewrite option enabled, to `/index.html`, with everything else disabled.

When loading `/`, it responds with a 301 redirect and empty `location` header.

**Comment by ethanaobrien** [comment]
Clear your cookies and tell me if this still occurs

**Comment by terreng** [comment]
> Clear your cookies and tell me if this still occurs (you must go into chrome settings and clear them, `301` responses are cached)

I did an empty cache and hard reload. The issue still occurs.
