### ISSUE TITLE
Sync config changes in real time

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#61]
Use `fs.watchFile` to detect changes to the config file. Update servers and UI in real time without needing to restart the program.

Perhaps show a banner on the main list / refresh button icon at the top. Click to reload from config file. Essentially just restarts the program. Detect changes to config outside of program.

**Comment by dougouverson** [comment]
It would be nice if when I save a file that the browser would auto-refresh.

**Comment by ethanaobrien** [comment]
>It would be nice if when I save a file that the browser would auto-refresh.

That couldn't be supported. The file would need to have javascript code thrown into it and keep a socket connection open with the server to know when to refresh. This issue is about the config file for the server settings, to refresh the app settings when the app settings are changed

**Comment by terreng** [comment]
> It would be nice if when I save a file that the browser would auto-refresh.

Thanks for the suggestion! This could be possible, but it would require injecting some additional code into the page, and would only work with .html files. I know that some JavaScript frameworks take this approach already, and it would certainly be handy to have the page update whenever you make a change. We'll consider adding this as an optional feature in a future release.

I went ahead and parked the idea in issue #106. Let us know if you have any additional ideas or suggestions!
