### ISSUE TITLE
Spa does not work with service worker when enabled.

### ISSUE THREAD

**Issue by WebScaffolder** [terreng/simple-web-server#70]
Hi,

Spa dose not work with service worker.

Generated service worker's cache file precache-manifest, store spa url with parameter, so reload of any page for SPA, it lost it's own cache link or get mismatch regexp link i think.

Any advice or fix can be appreciable.

**Comment by terreng** [comment]
@WebScaffolder This issue might have been fixed by Ethan in #57 or #73. Can you download the latest version and test again? Thanks!

**Comment by terreng** [comment]
@WebScaffolder Can provide more details / example code? Otherwise I will have to close the issue because I haven't found a problem.

**Comment by WebScaffolder** [comment]
Sorry for delay, shortly i will provide video demonstration.

**Comment by terreng** [comment]
That would be great! Please make sure to use the latest version of the new-ui branch.

**Comment by terreng** [comment]
@WebScaffolder Any update on this issue? A video demonstration or any other additional details would be very helpful. Thanks!

**Comment by WebScaffolder** [comment]
ok let me check.
Jamial Hasan

 
 
 

    On Tuesday, 22 March 2022, 03:01:59 GMT, Terren ***@***.***> wrote:  
 
 


@WebScaffolder This issue might have been fixed by Ethan in #57 or #73. Can you download the latest version and test again? Thanks!

**Comment by terreng** [comment]
@WebScaffolder Please let me know if you can check this. Simple Web Server is now released on the Microsoft Store, so you can test with the version if you'd like. Thanks!

**Comment by terreng** [comment]
@WebScaffolder I'm closing this issue because it has been over 50 days since we heard from you, and I don't have enough information to recreate the issue. Please feel free to comment with more information (such as the video demonstration you mentioned), and I'll reopen the issue.

**Comment by ethanaobrien** [comment]
@terreng based on the title, this would have been a problem with his code, not with the server
