### ISSUE TITLE
Minimize app size

### ISSUE THREAD

**Issue by ethanaobrien** [terreng/simple-web-server#71]
I'm wondering, when packaging, if there is a better way to store the thousands of node dependency files. This would drastically decrease file size and install speed.

Also, an auto updater would be a nice feature rather than just notifying the user

For both these examples, I think we should try to see how the discord desktop app does these things (Its electron based, in the app you can open the console by pressing `crtl`+`shift`+`i`,  or at least you used to in older versions of the app, they seem to have changed it)

**Comment by terreng** [comment]
> I'm wondering, when packaging, if there is a better way to store the thousands of node dependency files. This would drastically decrease file size and install speed.

I don't know of a better way to package node dependencies in an Electron app. Let me know if you find something.

> Also, an auto updater would be a nice feature rather than just notifying the user

I agree. This is easy to do with Electron, but it requires code signing, which I still haven't figured out. Without code signing, we need the user to download and install the new version themselves.

**Comment by ethanaobrien** [comment]
@terreng Ive been doing some digging on other ways to package the app. [ `electron-forge`](https://github.com/electron-userland/electron-forge) seems to be the most heavy of them all. I've found 2 additional packagers they have.


I havent had the ability to test yet, but this is what I've found based on the readme/other sources

[`electron-packager`](https://github.com/electron/electron-packager) - with this (unlike electron forge) we would have the ability to trim out unused modules.

[`electron-builder`](https://github.com/electron-userland/electron-builder) - claims to have an auto updater (and I think would automatically cut out everything we dont need)

**Comment by terreng** [comment]
I'm pretty sure I've used all three at some point or another. If I recall correctly, `electron-packager` wasn't as feature complete and it didn't provide a way to change the app icon. This might be different now, I'm not sure.

I believe both forge and builder have auto updater functionality. Although I'm pretty sure you still need code signing to do that either way.

> [electron-forge](https://github.com/electron-userland/electron-forge) seems to be the most heavy of them all

Did you find a build size comparison between them? It would be great if you might have found some numbers.

> with this (unlike electron forge) we would have the ability to trim out unused modules.

`electron-forge` is based on `electron-packager`, so if you can trim out unused modules with `electron-packager` you certainly can with `electron-forge` too. I don't think we have any unused modules though. By modules you mean node packages, right?

It would probably be a good idea for me to try out a build with `electron-builder` and see how it goes.

**Comment by ethanaobrien** [comment]
>If I recall correctly, electron-packager wasn't as feature complete and it didn't provide a way to change the app icon. This might be different now, I'm not sure.

Looks like they implemented this (https://github.com/electron/electron-packager/issues/1334). And yes, from what I've been looking its more raw then the other 2.

>Did you find a build size comparison between them? It would be great if you might have found some numbers.

I havent had a chance to test it yet. Ill get that to you when I do

>electron-forge is based on electron-packager, so if you can trim out unused modules with electron-packager you certainly can with electron-forge too. I don't think we have any unused modules though. By modules you mean node packages, right?

Yes, and yeah thats what I think too, but it is still taking up a crazy amount of space

>It would probably be a good idea for me to try out a build with electron-builder and see how it goes.

👍

**Comment by ethanaobrien** [comment]
We completed this when moving to electron from electron forge
