### ISSUE TITLE
Listen on IPV6

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#80]
Web Server for Chrome had an option called _Listen on IPV6_. 

https://www.grouparoo.com/blog/node-js-and-ipv6

**Comment by ethanaobrien** [comment]
from my understanding we would just need to set the host to `::` (that is what web server for chrome does)

**Comment by terreng** [comment]
Added in https://github.com/terreng/simple-web-server/pull/65/commits/0d810d4e46712ea9b1d98fae2ae771a604fb4051
