### ISSUE TITLE
Uncaught exception with HTTPS

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#87]
I turned on HTTPS for a server and generated a certificate for it. The next time I opened the app, this error came up. The server gets stuck in the "Starting..." state because this error isn't being caught. And the error comes up every time I try to start it. All the settings are on their defaults except for enabling HTTPS and auto generating a certificate.

```
Uncaught Exception:
Error: error:0900006e:PEM routines:OPENSSL_internal:NO_START_LINE
at Object.createSecureContext (_tls_common.js:129:17)
at Server.setSecureContext (_tls_wrap.js:1323:27)
at Server (_tls_wrap.js:1181:8)
at new Server (https.js:66:14)
at Object.createServer (https.js:91:10)
at createServer (/Users/terren/Documents/GitHub/web-server/index.js:382:44)
at createServers (/Users/terren/Documents/GitHub/web-server/index.js:363:13)
at startServers (/Users/terren/Documents/GitHub/web-server/index.js:358:9)
at App.<anonymous> (/Users/terren/Documents/GitHub/web-server/index.js:168:5)
at App.emit (events.js:315:20)
```

We need to figure out what's causing this error, and at the very least make sure we catch it and set the status of that server to errored.

**Comment by ethanaobrien** [comment]
It looks like the error is from within the https module itself.

According to [this](https://github.com/node-apn/node-apn/issues/234) the error should be caught though. Should we open an issue?

**Comment by terreng** [comment]
I'm pretty sure I tracked down the issue. I think it's because spaces get replaced with `\r\n`, even in the header.

```
-----BEGIN\r\nCERTIFICATE-----\r\nMIIC5jCCAk+gAwI.....
```

The issue only happens when you turn on https and generate a new cert, save it, and then restart the app. The next time it opens, it messes up the certificate.

Could you test this and see if you can reproduce the issue?

If you can, could you fix this? Probably just get rid of the option to use spaces instead of `\r\n` in certificates.

Seeing as we are supplying a bad certificate, this is probably the https module working as intended. I added a try catch to properly handle this error, as it may come up if a user tries to use a malformed custom certificate.

**Comment by ethanaobrien** [comment]
Yeah that is probably the problem, Ill take a look

**Comment by terreng** [comment]
@ethanaobrien You [fixed this in 83](https://github.com/terreng/simple-web-server/pull/83/commits/023a3471b5660f10e9f0ad64c2b270a885424aed), right?

**Comment by ethanaobrien** [comment]
Yes
