### ISSUE TITLE
spa custom regex expression

### ISSUE THREAD

**Issue by ethanaobrien** [terreng/simple-web-server#88]
I made a spa app and I now finally realize why you would want to have a custom regex expression.

The current one is `/.*\.[\d\w]+$/` which basically means if the file (it basically pops after the last `/`) has a `.` (dot) and then something after the dot then the spa page will not (since we want it to be null) be rendered. A custom regex would allow the user to only render the spa html with something like a certain extension or a specific folder in the path or something like this.

Going back to this (I couldnt find the exact location but I remember the conversation)

spa does NOT just render the page when no file is found, it renders the page when the regex expression is not met.

Let me know what you think

**Comment by terreng** [comment]
I understand how the custom regex feature works, as you've described. The reason I think we shouldn't add it is because it doesn't feel "simple". Very few users will need this feature. And those who do may already need more than it can offer, such as wanting to set up multiple different rewrites. This seems like the kind of thing that could instead be a per-directory htaccess-like option.

**Comment by ethanaobrien** [comment]
That is probably true. Do you want me to add it to the htaccess file? this is kind of already implemented (with the htaccess request versioning feature) or should we just leave it?

**Comment by terreng** [comment]
Let's leave it for now, and revisit it later.

**Comment by hardduty** [comment]
online wan features update

**Comment by hardduty** [comment]
wan port  sharing if port open router then  internal   lan ip     or external lan ip convert method please demonstration one youtube video local level access okay wan level level access many problems

**Comment by terreng** [comment]
@hardduty I don't understand what you're saying. Could you please open a new issue on GitHub? Could you please communicate more clearly?

**Comment by ethanaobrien** [comment]
I think he is asking how to make the website available on the internet and that he's having problems accessing it from another device on the same lan network.
