### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#89]
I've been having trouble getting the Linux build to work from arm64 Debian Linux. I'll have to look into it later.

- [ ] add linux file paths to logs and config.json pages

**Comment by ethanaobrien** [comment]
Just wanted to let you know, I just built a Deb (for debian) within my debian environment to install on that machine, and it both built and installed fine, so at least debian should be good to go

**Comment by stokito** [comment]
please send a pr with debian control files

**Comment by terreng** [comment]
Sorry I left this tab open but missed the comments. I fixed my build issue, it was really simple.

**Comment by terreng** [comment]
I built .deb, .rpm, and .zip. I think those are the main ones we need, but there are more flavors we can build if we want to.

They're published for the 1.2.9 release and on the website.

We might need to test file watching on Linux, I don't remember if that works. Also I previously disabled the "Show icon in system tray/menu bar" option because it caused the Linux build to crash I think.

**Comment by terreng** [comment]
I still need to figure out how to set the proper metadata including:
- App name
- Icon
- License

<img width="902" alt="Screenshot 2023-09-10 at 10 36 09 PM" src="https://github.com/terreng/simple-web-server/assets/11605395/3bdf147d-972e-4744-8f1f-79932e63ad91">

Also, I still need to add linux file paths to logs and config.json pages on the website.

**Comment by terreng** [comment]
@ethanaobrien Could you test the published Debian build and make sure it works?

**Comment by terreng** [comment]
We could also consider publishing to the Linux app stores, of which I am entirely unfamiliar.

**Comment by stokito** [comment]
The  amd64.deb works  on Ubuntu 23.04 with gnome flashback.

**Comment by ethanaobrien** [comment]
>We might need to test file watching on Linux, I don't remember if that works

Only recursive file watching is unsupported

>Could you test the published Debian build and make sure it works?

Yep, works fine.
