### ISSUE TITLE
Migrate from WSC

### ISSUE THREAD

**Issue by terreng** [terreng/simple-web-server#92]
Could you please open a new PR on [kzahel/web-server-chrome](https://github.com/kzahel/web-server-chrome) that does the following:

- Add a react UI card (like you already did on #264) that says "Chrome apps are going away! Web Server for Chrome is now a standalone program: https://simplewebserver.org"
  - Make the link text say "https://simplewebserver.org", but have the link actually go to https://simplewebserver.org/wsc.html
  - If possible, don't show this message to users on Chrome OS
- Update README.md to add the same message to the top of it.

Please make a separate PR with only these changes, because it will make it much easier for him to merge it.

Once I finish with the initial release, and you create the PR, then we can ask him if he could merge it and do a release on the chrome web store. Sound like a plan?

**Comment by ethanaobrien** [comment]
Sounds good. Ill work on this when I get a chance (should be tomorrow but that may change)

**Comment by terreng** [comment]
@ethanaobrien Would be great if you could do this soon. I'm working on the mac app store version (first submission got rejected), and hoping to have the initial release totally done in the next few days...

**Comment by ethanaobrien** [comment]
I should be able to do this today. The last time I sat down to do this, I couldn’t figure out the thing with the branches, so I plan to just dust off this other old GitHub account I literally never use and submit the pr there.

**Comment by terreng** [comment]
You should be able to create a new branch on your own fork of the project. You can then submit a pr from that branch, and the pr will be whatever is different between it and the master branch of the original repo. So you should create the new branch based on the original version of the original repo, before any changes you made for another pr.

**Comment by ethanaobrien** [comment]
I thought about doing that, but wouldn’t it still merge the 180 commits I have?

**Comment by terreng** [comment]
Not if you create a separate branch based on an earlier commit before your changes.

**Comment by ethanaobrien** [comment]
I didn’t know you could do that. Would I just find the last commit made when I cloned it and clone the branch from there?

**Comment by ethanaobrien** [comment]
Nevermind. I managed to clone it. Thank you! I didn’t know you could do that

**Comment by terreng** [comment]
On your fork of the repo, you can

1. View the commit history
<img width="175" alt="Screen Shot 2022-05-28 at 10 53 07 AM" src="https://user-images.githubusercontent.com/11605395/170837307-bc776673-bde6-4e71-a751-7e04c52fc647.png">

2. Click the "browse the repository at this point" button the newest commit that wasn't yours
<img width="365" alt="Screen Shot 2022-05-28 at 10 53 25 AM" src="https://user-images.githubusercontent.com/11605395/170837318-00597ff5-8c60-4e18-a24c-72c0ae75fbd9.png">

3. Make a new branch from that point
<img width="365" alt="Screen Shot 2022-05-28 at 10 53 47 AM" src="https://user-images.githubusercontent.com/11605395/170837334-b4e71c4c-6d7c-47dc-b20f-b2a1c3dd2342.png">

**Comment by ethanaobrien** [comment]
@terreng https://github.com/kzahel/web-server-chrome/pull/304

**Comment by terreng** [comment]
Great! Still working on the macOS app store release. Two rejections now. Hopefully I'll work it out soon.
